### ISSUE TITLE
Connect hub by using USB

### ISSUE THREAD

**Issue by ttn-c4plus** [FLL-Team-24277/Master-Program-Fall-2023#1]
Hello, I have a problem with hub connection. By following your step, I have to connect to hub with Bluetooth. How can I use USB to connect to hub and download program.

**Comment by ttn-c4plus** [comment]
Is there any way to contact with you?
My email: c4plus.ttn@gmail.com

**Comment by FLL-Team-24277** [comment]
Hi, I answered your question in chat, but I am pasting it here again:
I don't see using bluetooth to download programs at FLL competitions a problem. The rules don't permit using bluetooth to CONTROL the robot during the robot game. But when you are in the pits, updating your program over USB is perfectly OK.

**Comment by ttn-c4plus** [comment]
Sorry about my mistake. The WRO National competition in Viet Nam, they didn't allow to use Bluetooth. So if it true, how can I following your guide to use vscode, pybrick libraries and USB to download to the hub.

**Comment by FLL-Team-24277** [comment]
Ahh, sorry for the misunderstanding. First of all, I don't think there is a way to completely disable the BT radio on the Spike hub--no matter what firmware you are using. You didn't say which hub you were using, so that may not be an issue for you. 

Anyway, to answer your question, the instructions I am using in this repo uses a command line program called pybricksdev.exe to upload the programs to the hub. To install in, just run `pip install pybricksdev`. Once you do that, you can type `pybricksdev.exe run -h` and it will show the command line options for how to run the program you have written on your robot, including how to use USB. I don't use USB myself, so I don't have any experience with it, but it looks easy enough.

I hope that helps. Write back if you have any other questions, or need clarification for anything.

**Comment by FLL-Team-24277** [comment]
```
(.venv) PS C:\Github-Projects\Master-Program-Fall-2023> pybricksdev run -h
usage: pybricksdev.exe run [-h] [-n <name>] [--wait | --no-wait] <connection type> <file>

positional arguments:
  <connection type>     connection type: ble, usb, ssh
  <file>                path to a MicroPython script or `-` for stdin

options:
  -h, --help            show this help message and exit
  -n <name>, --name <name>
                        hostname or IP address for SSH connection; Bluetooth device name or Bluetooth address for BLE connection; serial port name for USB       
                        connection
  --wait, --no-wait     wait for the program to complete before disconnecting (default: True)
(.venv) PS C:\Github-Projects\Master-Program-Fall-2023> 
```

**Comment by ttn-c4plus** [comment]
Awesome, I will try now. Thank you

**Comment by ttn-c4plus** [comment]
A problem, when I install pybrick firmware, I cant see COM PORT USB,

**Comment by FLL-Team-24277** [comment]
Sounds like maybe you haven't installed the USB driver. Are you using a Spike Prime? If so, there is a USB driver that must be manually installed before you can upload the firmware. I've done this many times and it has always worked. Click the instructions link in the yellow box at the bottom
![image](https://github.com/FLL-Team-24277/Master-Program-Fall-2023/assets/110741729/1a55a403-ce96-43a4-8290-3cd9d6694586)

**Comment by ttn-c4plus** [comment]
oh, I did it, I already installed USB driver and the firmware of pybrick.

How about command line to download file to hub:
`pybricksdev.exe run -n Robot_name --no-wait usb file_name.py`
Is it right??

**Comment by FLL-Team-24277** [comment]
I've never done this with USB before, so I am totally guessing here. From the help, it says the -n <NAME> for usb should be the serial port name
```
-n <name>, --name <name>
                        hostname or IP address for SSH connection; Bluetooth device name or Bluetooth address for BLE connection; serial port name for USB       
                        connection
```
So I think the name in this case would be something like "COM3", and not your robot name. You can plug your robot in and go to your Device Manager and look under "Ports (COM and LPT)" to see if you can figure out what the COM port is. Maybe plug it in and unplug it to see which one comes up.

Also, know that the COM port can change from time to time. So if it is COM3 today, tomorrow it might be a different port. USB COM ports can be funny like that.

If the COM port name doesn't solve your problem, you will probably need to work with the pybricks folks to see if they can get you connected.

**Comment by ttn-c4plus** [comment]
thank you, I will try all of them. 
If you have another way to contact, such as fb or anyway to send a message please give me, I have to solve this problem :(. because I have more than 2 week to competition days
My fb: (https://www.facebook.com/ttn.c4plus)

**Comment by FLL-Team-24277** [comment]
Honestly the best way to get a hold of me is right here. I'll keep helping as long as I have help to offer! I am hoping this works out for you, so please keep me posted.

**Comment by ttn-c4plus** [comment]
Hello, I try to plug in and unplug USB cable, and nothing change. 
Or maybe the firmware of pybrick, they disabled connect USB for hub. 
Can you try to use your hub and plug in USB cable, if you can't see. the firmware was disabled it.
Please try for me

**Comment by ttn-c4plus** [comment]
Or maybe I have to use hub 2.0 and [BaseRobotFall2022](https://github.com/FLL-Team-24277/BaseRobotFall2022/tree/main)
And do everything from scratch :(. so sad

**Comment by FLL-Team-24277** [comment]
I am seeing the same thing. When I plug my hub in and connect it with USB, nothing changes in the COM port section of the Device Manager. I'll post something in the pybricks support to see if we are missing a step.

My BaseRobot Fall2022 did not use pybricks. It used the Lego firmware with python support. I wouldn't use that just yet.

**Comment by ttn-c4plus** [comment]
Yes, I hope they can update to use USB connect in the future. Now, I just wait for National Organize.
